In [1]:
#We create a list called "Distance" and "Time"
distance = [10,15,17,26]
time = [.30,.47,.55,1.20]

---

In [2]:
#Deleting Elements of a list
list1 =[2,4,5,8,9,7]

In [3]:
del list1[2:5]

In [4]:
print(list1)

[2, 4, 7]


In [5]:
#Numpy ndarrays are better than lists as mathematical functions can be applied 
import numpy as np

In [6]:
np_distance=np.array(distance)

In [7]:
np_time= np.array(time)

In [8]:
speed = np_distance/np_time

In [9]:
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

In [49]:
#In NumPy, a scalar is any object that you put in an array.
#NumPy ensures all scalars in an array have same types.
#The basic ndarray is created using an array function in NumPy as follows −

#numpy.array 

In [10]:
#The NumPy array object has a property called dtype that returns the data type of the array:
import numpy as np

arr1 = np.array([8, 9, 3, 4])

print(arr1.dtype)


int32


In [11]:
#Get the data type of an array containing strings:

import numpy as np

arr2 = np.array(['apple', 'banana', 'cherry'])

print(arr2.dtype)

<U6


-----

#numpy.ndarray.ndim() function return the number of dimensions of an array.

In [12]:
import numpy as np
  
arr1 = np.array([1, 2, 3, 4])
  
bcd = arr1.ndim
  
print (bcd)

1


In [53]:
import numpy as np
  
arr2 = [[1, 2, 3], [4, 5, 6]]
  
efg = np.ndim(arr2)
  
print (efg)

2


In [13]:
np_city = np.array(['NYC','LA','Miami','Houston'])

In [14]:
np_city.ndim           #gives the number of dimensions of the ndarray

1

In [15]:
np_city_with_state = np.array([['NYC','LA','Miami','Houston'],['NY','CA','FL','TX']])

In [16]:
np_city_with_state.ndim

2

#ndarray.shape
#This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array.

In [17]:
import numpy as np 
l = np.array([[1,2,3],[4,5,6]]) #which means that the array has 2 dimensions, 
                                #where the first dimension has 2 elements and the second has 3.
print (l.shape)

(2, 3)


In [18]:
# this resizes the ndarray l
import numpy as np 

m = np.array([[1,2,3],[4,5,6]])  #In python,the default is row wise filling.
m.shape = (3,2) 
print(m)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
#Reshaping arrays
#Reshaping means changing the shape of an array.
#The shape of an array is the number of elements in each dimension.
#By reshaping we can add or remove dimensions or change number of elements in each dimension.



In [20]:
#Convert the following 1-D array with 12 elements into a 2-D array.

#The outermost dimension will have 4 arrays, each with 3 elements:

import numpy as np

arr51 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr51.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
#Convert the following 1-D array with 12 elements into a 3-D array.

#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

import numpy as np

arr52 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr1 = arr52.reshape(2, 2, 3) #the first component is the number of matrices(read:arrays),second rows,third columns
                                  # Arrays are a collection of matrices()
print(newarr1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [22]:
#Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension
import numpy as np

arr53 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr3 = arr53.reshape(2,4)

print(newarr3)

[[1 2 3 4]
 [5 6 7 8]]


In [23]:
#We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array 
#but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.
import numpy as np

arr54 = np.array([1, 2, 3, 4, 5, 6, 7, 8])  

newarr4 = arr54.reshape(4, 2)

print(newarr4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [24]:
#Example
np_city = np.array(['NYC','LA','Miami','Houston'])
np_city.shape


(4,)

In [25]:
np_city_with_state = np.array([['NYC','LA','Miami','Houston'],['NY','CA','FL','TX']])
np_city_with_state.shape


(2, 4)

NDARRAYS-SIZE ATTRIBUTE

In [26]:
#In Python, numpy.size() function count the number of elements along a given axis.
# importing numpy
import numpy as np
 
# Creating a random array
arr55 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
 
# By default, give the total number of elements.
print(np.size(arr55))

8


In [68]:
import numpy as np
 
arr56 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
 
# count the number of elements along the axis.
# Here rows and columns are being treated
# as elements
 
#gives no. of rows along x-axis
print(np.size(arr56, 0))   #0 and 1 denotes the x and y axis respectively
 
#gives no. of columns along y-axis
print(np.size(arr56, 1))

2
4


In [27]:
#Example
np_city = np.array(['NYC','LA','Miami','Houston'])
np_city.size

4

In [28]:
np_city_with_state = np.array([['NYC','LA','Miami','Houston'],['NY','CA','FL','TX']])
np_city_with_state.size


8

#The dtype() function is used to create a data type object. A numpy array is homogeneous, and contains elements described by a dtype object. 
#A dtype object can be constructed from different combinations of fundamental numeric types.

In [29]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])

print(arr1.dtype)

int32


In [72]:
#Integers – This value is represented by int class. 
#It contains positive or negative whole numbers (without fraction or decimal). 
#In Python there is no limit to how long an integer value can be.

In [31]:
import numpy as np

arr2 = np.array(['apple', 'banana', 'cherry'])      #Unicode is a universal character encoding standard. It defines the way individual characters are represented in text files, web pages,etc

print(arr2.dtype)

<U6


In [74]:
#Creating Arrays With a Defined Data Type
import numpy as np

arr3 = np.array([1, 2, 3, 4], dtype='S')     #b in output stands for bytes
                                             #Strings can be used to represent data like special characters, characters,
print(arr3)                                  #Bytes are used to represent low-level binary data structures.
print(arr3.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [33]:
#Create an array with data type 4 bytes integer:
import numpy as np

arr4 = np.array([1, 2, 3, 4], dtype='i4')##int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc. 

print(arr4)
print(arr4.dtype)

[1 2 3 4]
int32


In [34]:
#Basic Operations using Numpy
#Vector addition of Arrays
first_trial_cyclist = [10,15,17,26]
second_trail_cyclist = [12,11,21,24]

## Accesing array elements by indexing

In [35]:
import numpy as np

np_first_trial_cyclist= np.array(first_trial_cyclist)

np_second_trail_cyclist= np.array(second_trail_cyclist)

In [36]:
total_distance = np_first_trial_cyclist+np_second_trail_cyclist

In [37]:
total_distance

array([22, 26, 38, 50])

In [38]:
#Creating a 2D array using cyclist data
cyclist_trials = np.array([[10,15,17,26],[12,11,21,24]])
first_trial = cyclist_trials[0]             #We are selectively fetching the list from the array.This list can be treated
first_trial                                  #as a subset of the main 2D array

array([10, 15, 17, 26])

In [39]:
second_trial = cyclist_trials[1]

In [40]:
second_trial

array([12, 11, 21, 24])

In [41]:
first_cyclist_first_trial = cyclist_trials[0][0]  # Gives us the 1st element of the first list

In [42]:
first_cyclist_first_trial

10

In [43]:
first_cyclist_all_trials = cyclist_trials[:,0]    #the : operator selects all the rows,

In [44]:
first_cyclist_all_trials

array([10, 12])

## Slicing to access a range of values and create a subset

In [45]:
cyclist_trials.shape           #shape function tells us the array will have 2 rows and 4 columns

(2, 4)

In [46]:
two_cyclist_trail_data = cyclist_trials[:,1:3]  #In this case all rows but only col 1,2 data will be fetched
                                                #the ':' indicator states that all rows will be selected

In [47]:
cyclist_trials

array([[10, 15, 17, 26],
       [12, 11, 21, 24]])

In [48]:
two_cyclist_trail_data

array([[15, 17],
       [11, 21]])

In [135]:
#Loop Through the Index Numbers
#We can also loop through the list items by referring to their index number.

#Use the range() and len() functions to create a suitable iterable.

In [49]:
mylist = ["red", "blue", "green"]
for i in range(len(mylist)):
  print(mylist[i])

red
blue
green


In [50]:
#While loop
#Using a While Loop
#We can loop through the list items by using a while loop.

#Use the len() function to determine the length of the list, then start at 0 and loop your way through the list items 
#by refering to their indexes.

#Increase the index by 1 after each iteration.

In [94]:
mylist = ["red", "blue", "green"]
i = 0
while i < len(mylist):
  print(mylist[i])
  i = i + 1

red
blue
green


In [53]:
two_cyclist_trail_data

array([[15, 17],
       [11, 21]])

In [52]:
for iterate_cyclist_trials_data in cyclist_trials:        #Iterating over all the values in the dataset using For Loop
    print(iterate_cyclist_trials_data)

[10 15 17 26]
[12 11 21 24]


In [97]:
#indexing with Boolean arrays

In [54]:
#We have student 1 with scores 83,71,57,63 and student 2 with scores 54,68,81,45
test_scores = np.array([[83,71,57,63],[54,68,81,45]])


In [55]:
passing_score = test_scores > 60

In [56]:
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [57]:
#the test scores which are greater than 60
test_scores[passing_score]

array([83, 71, 63, 68, 81])

In [102]:
#The Difference Between Copy and View
#The main difference between a copy and a view of an array is that the copy is a new array, 
#and the view is just a view of the original array.

#The copy owns the data and any changes made to the copy will not affect original array, 
#and any changes made to the original array will not affect the copy.

#The view does not own the data and any changes made to the view will affect the original array, 
#and any changes made to the original array will affect the view.

In [58]:
#Make a copy, change the original array, and display both arrays:

import numpy as np
arr9 = np.array([6,7,8,9,10])      #The copy SHOULD NOT be affected by the changes made to the original array.
x = arr9.copy()
arr9[0] = 45
print(arr9)
print(x)

[45  7  8  9 10]
[ 6  7  8  9 10]


In [59]:
#Make a view, change the view, and display both arrays:

import numpy as np

arr10 = np.array([1, 2, 3, 4, 5])     #The original array SHOULD be affected by the changes made to the view.
x = arr10.view()
x[0] = 31

print(arr10)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [60]:
#Every NumPy array has the attribute base that returns None if the array owns the data.

#Otherwise, the base  attribute refers to the original object.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [61]:
#When working with arrays, data is copied into new arrays only in some cases. Following are the three possible scenarios:
#In this method, a variable is directly assigned the value of another variable. No new copy is made.

import numpy as np
NYC_Borough = np.array(['Manhattan','Bronx','Brooklyn','Staten Island','Queens'])



In [62]:
NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [63]:
#renaming

Boroughs_In_NYC=NYC_Borough

In [64]:
Boroughs_In_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [65]:
#Checking with the Boolean operators

Boroughs_In_NYC is NYC_Borough

True

In [66]:
views_in_Boroughs_In_NYC=Boroughs_In_NYC.view()

In [67]:
len(views_in_Boroughs_In_NYC)

5

In [68]:
views_in_Boroughs_In_NYC[4] = 'Central Park'

In [69]:
print(views_in_Boroughs_In_NYC)

['Manhattan' 'Bronx' 'Brooklyn' 'Staten Island' 'Central Park']


In [70]:
print(Boroughs_In_NYC)            #Changes made in the view will amend the original array,as view does not own data

['Manhattan' 'Bronx' 'Brooklyn' 'Staten Island' 'Central Park']


In [71]:
#Copy of Original Array
copy_NYC_Borough = NYC_Borough.copy()

In [72]:
copy_NYC_Borough is NYC_Borough     #Copy is a deep copy of original array and not same as the original array

False

In [73]:
copy_NYC_Borough.base is NYC_Borough #the copy of the array is NOT owned by the original array

False

In [74]:
copy_NYC_Borough[4] = 'Main Park'

In [75]:
copy_NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Main Park'],
      dtype='<U13')

In [76]:
NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

## Basic operations of a Numpy Array-Demo

In [77]:
import numpy as np

In [78]:
#addition
np.add(45,20)

65

In [79]:
#Subtraction
np.subtract(45,23)

22

In [80]:
#We compute the daily wage of a lobour,with the hours worked for 5 days,and a payment of $15 dollars per hour.
daily_wage = np.array([15,16,17,18,19])*15

In [81]:
daily_wage

array([225, 240, 255, 270, 285])

In [82]:
#to find the total earnings in 5 days
sum(daily_wage)

1275

## Comparison Operators

In [83]:
#Create an array which shows how many hours per week has been worked,for 5 consequetive weeks
np_weekly_hrs= np.array([23,41,55,47,38])

In [84]:
#no of weeks were the person worked more than 40 hours
np_weekly_hrs>40

array([False,  True,  True,  True, False])

In [85]:
#To get the actual number of hours
np_weekly_hrs[np_weekly_hrs>40]

array([41, 55, 47])

In [86]:
#weeks when the person did not work for 40 hours,here we get subset of the main data
np_weekly_hrs[np_weekly_hrs!=40]

array([23, 41, 55, 47, 38])

## Logical operations with Numpy

In [87]:
#Say we want to find out in how many weeks the person worked for more than 20 hours and less than 50 hours
#We will use the AND operator,and the result will be a boolean value.
np.logical_and(np_weekly_hrs>20,np_weekly_hrs<50)

array([ True,  True, False,  True,  True])

In [88]:
#We want to find how in which weeks the hours worked by the person did not exceed 35 hours.
np.logical_not(np_weekly_hrs>35)

array([ True, False, False, False, False])

## Universal Functions (Ufunc).ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.Vectorization is a technique of implementing array operations without using for loops.

In [89]:
#numpy.sqrt(array[, out]) function is used to determine the positive square-root of an array, element-wise.
import numpy as me
first_array = me.sqrt([4,81,64,25])
first_array

array([2., 9., 8., 5.])

In [90]:
#the sqrt function does not work for negetive numbers
import numpy as np
array2 = np.sqrt([-4, 5, -6])
array2

C:\Users\Lenovo\AppData\Local\Temp/ipykernel_1400/3842107405.py:3: RuntimeWarning: invalid value encountered in sqrt
  array2 = np.sqrt([-4, 5, -6])


array([       nan, 2.23606798,        nan])

## Trigonometric Functions-NumPy provides the ufuncs sin(), cos() and tan()  to  produce the corresponding sin, cos and tan values.

In [91]:
#numpy.cos-This mathematical function helps us to calculate trigonometric cosine for all x(being the array elements).
# array elements are in radians. 2pi Radians = 360 degrees
import numpy as np

 
cs_array = [0, np.pi / 2, np.pi / 3, np.pi]
cs_array

[0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

In [92]:
#using sine function
import numpy as np

array1 = np.array([np.pi/2, np.pi/5])

x = np.sin(array1)

print(x)

[1.         0.58778525]


In [93]:
#Floor functions--This function returns the floor value of the input array elements. 
#The floor of a number x is i if i is the largest integer such that, i<=x.
import numpy as np  
  
arr = [0.23, 0.09, 1.2, 1.24, 9.99] 

fl_arr = np.floor(arr) 

print(fl_arr)

[0. 0. 1. 1. 9.]


In [94]:
#Inverse of a matrix or array
import numpy as np        #only for square matrices

x = np.array([[5,3],[8,9]]) 
y = np.linalg.inv(x) 
print (x)
print (y) 
print (np.dot(x,y))

[[5 3]
 [8 9]]
[[ 0.42857143 -0.14285714]
 [-0.38095238  0.23809524]]
[[1. 0.]
 [0. 1.]]


In [95]:
import numpy as mat
array1 = mat.array([[10,20],[15,25]])
inv_array1 = mat.linalg.inv(array1)



In [96]:
mat.matmul(array1,inv_array1)  #the matrix/array multiplied by its inverse will always give an identity matrix as result

array([[1., 0.],
       [0., 1.]])