In [1]:
x=2
x

2

In [2]:
type(x)

int

In [3]:
y=2.5
y

2.5

In [4]:
a="Hello"
a

'Hello'

In [5]:
B='23'
B

'23'

In [6]:
type(a)
type(B)

str

In [7]:
q1=True
q2=False

In [8]:
type(q1)

bool

In [9]:
type(q2)

bool

In [10]:
n=100
type(n)
f=float(n)
print(n)
print(type(n))

s=str(n)
print(s)
print(type(s))

100
<class 'int'>
100
<class 'str'>


In [72]:
s='132.65'
n=int(float(s))
print(n)
print(type(n))
f=float(s)
print(type(f))

132
<class 'int'>
<class 'float'>


In [11]:
my_tuple=("AA","AB","AC",4,6,8,9,True)
print(my_tuple)
print(type(my_tuple))

my_tuple1=("AA","AB","AC",4,6,8,'10',"AA","AB",True,False)
print(my_tuple1)
print(type(my_tuple1))

print(len(my_tuple))
print(len(my_tuple1))

a=('tppl',)
print(type(a))
b=('tppl')
print(type(b))

print(my_tuple[4])
print(my_tuple1[10])

print(my_tuple[-1])
print(my_tuple1[-2])

print(my_tuple[1:4])
print(my_tuple[:4])
print(my_tuple[1:-1])

('AA', 'AB', 'AC', 4, 6, 8, 9, True)
<class 'tuple'>
('AA', 'AB', 'AC', 4, 6, 8, '10', 'AA', 'AB', True, False)
<class 'tuple'>
8
11
<class 'tuple'>
<class 'str'>
6
False
True
True
('AB', 'AC', 4)
('AA', 'AB', 'AC', 4)
('AB', 'AC', 4, 6, 8, 9)


In [12]:
first_list=['Mark',1,45,67,'show','cena']
print(first_list)
first_list.append('rock')
print(first_list)
first_list.remove('show')
print(first_list)
first_list.pop(0)
print(first_list)
first_list.insert(1,'orton')
print(first_list)
print(first_list[3])
print(first_list[-2])
print(first_list[1:4])
print(first_list[1:-1])

['Mark', 1, 45, 67, 'show', 'cena']
['Mark', 1, 45, 67, 'show', 'cena', 'rock']
['Mark', 1, 45, 67, 'cena', 'rock']
[1, 45, 67, 'cena', 'rock']
[1, 'orton', 45, 67, 'cena', 'rock']
67
cena
['orton', 45, 67]
['orton', 45, 67, 'cena']


In [13]:
first_dict={'john':'john@abc.in','Kelly':'kelly@ghj.com','id':[23,81]}
print(first_dict)
print(first_dict.keys())
print(first_dict.values())
print(first_dict['john'])
print(first_dict['id'])
first_dict.update({'id':[32,18]})
print(first_dict)
del first_dict['id']
print(first_dict)

{'john': 'john@abc.in', 'Kelly': 'kelly@ghj.com', 'id': [23, 81]}
dict_keys(['john', 'Kelly', 'id'])
dict_values(['john@abc.in', 'kelly@ghj.com', [23, 81]])
john@abc.in
[23, 81]
{'john': 'john@abc.in', 'Kelly': 'kelly@ghj.com', 'id': [32, 18]}
{'john': 'john@abc.in', 'Kelly': 'kelly@ghj.com'}


In [14]:
autosurvey=set(['audi','bmw','ferrari','ford','mercedes','mercedes'])
print(autosurvey)
print(type(autosurvey))
autosurvey1={'ferrari', 'mercedes', 'ford', 'bmw', 'audi'}
autosurvey2={'ferrari','mercedes','lamborghini','audi','porsche',4,'skoda'}
combinedset=autosurvey1 | autosurvey2
print(combinedset)
commonset=autosurvey1 & autosurvey2
print(commonset)

{'mercedes', 'ferrari', 'audi', 'bmw', 'ford'}
<class 'set'>
{'mercedes', 'ferrari', 4, 'skoda', 'audi', 'lamborghini', 'porsche', 'bmw', 'ford'}
{'mercedes', 'audi', 'ferrari'}


In [15]:
first_list=['Mark',1,45,67,'show','cena']
print('Mark' in first_list)
print('t' in 'encycloedia')

True
False


In [78]:
list1=['Mark',1,45,67,'show','cena']
list2=['audi','bmw','ferrari','ford','mercedes','mercedes']
a=list1+list2
print(a)
s=[1,2,3,4]
v=[5,6,7,8]
c=s+v
print(c)

firstname='likith'
lastname='vinayaka'
fullname=firstname+' '+lastname
print(fullname)

['Mark', 1, 45, 67, 'show', 'cena', 'audi', 'bmw', 'ferrari', 'ford', 'mercedes', 'mercedes']
[1, 2, 3, 4, 5, 6, 7, 8]
likith vinayaka


In [79]:
a=[1,2,3,4,5]*3
print(a)
b='friend'*5
print(b)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
friendfriendfriendfriendfriend


In [2]:
def sum(a,b):
    c=a+b
    return c
c=sum(4,5)
print(c)

def profile():
    age=24
    height=181
    weight=94
    return age,height,weight
print(profile())

def fname(a,b):
    fname1=a+' '+b
    return fname1
print(fname('bruce','lee'))

9
(24, 181, 94)
bruce lee


In [12]:
x=('apple','mango','pine')
y=enumerate(x)
print(tuple(y))

for pos,name in enumerate(x):
    print(pos,name)

store=dict((name,pos) for pos,name in enumerate(x))
print(store)

((0, 'apple'), (1, 'mango'), (2, 'pine'))
0 apple
1 mango
2 pine
{'apple': 0, 'mango': 1, 'pine': 2}


In [1]:
for i in range(6):
    print('Hi There')

Hi There
Hi There
Hi There
Hi There
Hi There
Hi There


In [3]:
range(5)

range(0, 5)

In [4]:
for i in range(6):
    print(i)

0
1
2
3
4
5


In [16]:
mylist=[10,100,1000]

for j in mylist:
    print('j is equal  to:',j)

j is equal  to: 10
j is equal  to: 100
j is equal  to: 1000


In [17]:
list(range(5))

[0, 1, 2, 3, 4]

In [18]:
for i in 'simplilearn':
    print(i)

s
i
m
p
l
i
l
e
a
r
n


In [19]:
subjects=['physics','chemistry','mathematics','computer science','english','kannada']
for i in subjects:
    print(i)
    if i == 'mathematics':
        print(i)
        break

physics
chemistry
mathematics
mathematics


In [20]:
subjects=['physics','chemistry','mathematics','computer science','english','kannada']
for i in subjects:
    if i == 'mathematics':
        continue
    print(i)

physics
chemistry
computer science
english
kannada


In [21]:
for i in range(8):
    print(i)
else:
    print("loop exit")

0
1
2
3
4
5
6
7
loop exit


In [22]:
for i in range(8):
    if i==5:
        break
    print(i)
else:
    print("loop exit")

0
1
2
3
4


In [ ]:
while True:
    print('Hello')

In [1]:
count=0
while count<12:
    print('count=',count)
    count+=1

count= 0
count= 1
count= 2
count= 3
count= 4
count= 5
count= 6
count= 7
count= 8
count= 9
count= 10
count= 11


In [4]:
x=0
while x<6:
    print('count is=',x)
    x+=1
print('Looping Done')

count is= 0
count is= 1
count is= 2
count is= 3
count is= 4
count is= 5
Loopin Done


In [8]:
count=0
while count<5:
    print(count,'is less than 5')
    count+=1
else:
    print(count,'is not less than 5')

0 is less than 5
1 is less than 5
2 is less than 5
3 is less than 5
4 is less than 5
5 is not less than 5


In [9]:
count=0
while count<5:
    print(count,'is less than 5')
    count+=1
print(count,'is not less than 5')

0 is less than 5
1 is less than 5
2 is less than 5
3 is less than 5
4 is less than 5
5 is not less than 5


In [27]:
distance=[10,20,30,40,50]
time=[0.3,0.6,0.9,0.12,0.15]

import numpy as np

np_distance=np.array(distance)
np_time=np.array(time)

speed=np_distance/np_time
print(speed)

twod=np.array([[1,2,3,4],[5,6,7,8]])
print(np_distance.ndim)
print(np_distance.shape)
print(np_distance.size)
print(np_distance.dtype)
print(twod.ndim)
print(twod.shape)
print(twod.size)
print(twod.dtype)

[ 33.33333333  33.33333333  33.33333333 333.33333333 333.33333333]
1
(5,)
5
int64
2
(2, 4)
8
int64


In [7]:
import numpy as np
l=np.array([1,2,3,4,5,6,7,8,9,10])
newr=l.reshape(5,2)
print(newr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [21]:
import numpy as np
m=np.array([[10,12,11,1,2,3],[1,2,46,67,89,90]])
k=m.reshape(4,3)
a=m[0]
b=m[0][3]
print(a)
print(b)
print(k)
q=m[:,1:3]
print(q)

[10 12 11  1  2  3]
1
[[10 12 11]
 [ 1  2  3]
 [ 1  2 46]
 [67 89 90]]
[[12 11]
 [ 2 46]]


In [20]:
import numpy as np

a=[1,2,3,4,5,6]
b=[6,7,8,9,0,1]
p=np.array(a)
q=np.array(b)
c=a+b
print(c)

[1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 0, 1]


In [26]:
import numpy as np
m=np.array([[10,12,11,1,2,3],[1,2,46,67,89,90]])
q=m[0:4,3:6]
print(q)

[[ 1  2  3]
 [67 89 90]]


In [30]:
import numpy as np
l=np.array([1,2,3,4,5,6,7,8,9,10])
s=l>6
print(s)
print(s.dtype)
l[s]


[False False False False False False  True  True  True  True]
bool


array([ 7,  8,  9, 10])