In [1]:
import numpy as np

In [4]:
first_numpy_array=np.array([1,2,3,4])

In [5]:
print(first_numpy_array)

[1 2 3 4]


In [6]:
array_with_zeros=np.zeros((3,3))

In [7]:
print(array_with_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
array_with_ones=np.ones((3,3))

In [10]:
print(array_with_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
array_empty=np.empty((2,3))
array_empty

array([[4.68750141e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [14]:
np_arange=np.arange(12)
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
np_linspace=np.linspace(1,6,5)
print(np_linspace)

[1.   2.25 3.5  4.75 6.  ]


In [18]:
np_oneD=np.arange(15)
np_oneD

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
np_twoD=np_oneD.reshape(3,5)
np_twoD

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
np_threeD=np.arange(27).reshape(3,3,3)
np_threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [23]:
np.add(45,23)

68

In [24]:
np.subtract(45,23)

22

In [27]:
np_wage=np.array([1,2,3,4,5])*5
np_wage

array([ 5, 10, 15, 20, 25])

In [28]:
np.sum(np_wage)

75

In [29]:
sum(np_wage)

75

In [30]:
np_whrs=np.array([45,23,67,34,75])

In [31]:
np_whrs[np_whrs>40]

array([45, 67, 75])

In [33]:
np_whrs[np_whrs!=40]

array([45, 23, 67, 34, 75])

In [34]:
np.logical_and(np_whrs>40,np_whrs<50)

array([ True, False, False, False, False])

In [35]:
np.logical_not(np_whrs>35)

array([False,  True, False,  True, False])

In [37]:
np_sqrt=np.sqrt([1,2,3,4,5,6])
np_sqrt

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [39]:
from numpy import pi
np.cos(0)

1.0

In [40]:
np.sin(pi/2)

1.0

In [41]:
np.cos(pi)

-1.0

In [42]:
np.floor([1.6,1.6,2.3,3.5,1.7,2.1])

array([1., 1., 2., 3., 1., 2.])

In [44]:
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])